import { z } from "zod";

const displayNameField = z
  .string()
  .trim()
  .min(1, "Display name is required")
  .max(24, "Display name must be 24 characters or fewer");

// Stable per-browser id generated by the frontend (localStorage-backed).
// Used server-side to stop the same person taking multiple seats in one
// event's active rooms - see services/roomService.ts.
const deviceIdField = z.string().trim().min(1).max(100);

// Only ever a URL this server itself handed out via POST /api/avatars/signature
// (see services/avatarService.ts) - restricting the host prevents someone
// pointing avatarUrl at an arbitrary/tracking/oversized image that would
// then get broadcast to every other participant in the room.
const avatarUrlField = z
  .string()
  .trim()
  .max(500)
  .refine((url) => {
    try {
      return new URL(url).hostname === "res.cloudinary.com";
    } catch {
      return false;
    }
  }, "avatarUrl must be a res.cloudinary.com URL")
  .optional();
const avatarPublicIdField = z.string().trim().min(1).max(300).optional();

// Optional - only present when the host tags their room's location on
// creation (see frontend RoomsLobbyPage's "tag my location" toggle, and
// the "Live near you" search embedded in the Events page). Either lat+lng,
// or country (+ optional city), or both.
const locationField = z
  .object({
    lat: z.number().min(-90).max(90).optional(),
    lng: z.number().min(-180).max(180).optional(),
    country: z.string().trim().min(1).max(60).optional(),
    city: z.string().trim().min(1).max(80).optional(),
  })
  .refine(
    (loc) =>
      (loc.lat !== undefined && loc.lng !== undefined) ||
      loc.country !== undefined,
    { message: "location needs either lat+lng or a country" },
  )
  .optional();

export const createRoomSchema = z
  .object({
    eventId: z.string().trim().min(1),
    roomName: z.string().trim().min(1, "Room name is required").max(60),
    visibility: z.enum(["public", "private"]),
    password: z
      .string()
      .trim()
      .min(4, "Password must be at least 4 characters")
      .max(50)
      .optional(),
    displayName: displayNameField,
    deviceId: deviceIdField,
    avatarUrl: avatarUrlField,
    avatarPublicId: avatarPublicIdField,
    location: locationField,
  })
  .superRefine((input, ctx) => {
    if (input.visibility === "private" && !input.password) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: "Private rooms need a password",
        path: ["password"],
      });
    }
  });

export const joinRoomSchema = z.object({
  competitionId: z.string().trim().min(1),
  displayName: displayNameField,
  password: z.string().trim().max(50).optional(),
  deviceId: deviceIdField,
  avatarUrl: avatarUrlField,
  avatarPublicId: avatarPublicIdField,
});

export const reconnectSchema = z.object({
  competitionId: z.string().trim().min(1),
  participantId: z.string().trim().min(1),
  participantToken: z.string().trim().min(1),
});

export const scoreUpdateSchema = z.object({
  competitionId: z.string().trim().min(1),
  participantId: z.string().trim().min(1),
  participantToken: z.string().trim().min(1),
  round: z.number().int().min(1),
  score: z.number().min(0).max(100000),
  status: z.enum(["RUNNING", "PAUSED", "DONE"]).optional(),
});

export const leaveCompetitionSchema = z.object({
  competitionId: z.string().trim().min(1),
  participantId: z.string().trim().min(1),
  participantToken: z.string().trim().min(1),
});

// Host-only "start now" for a room that hasn't filled to maxParticipants
// yet, gated server-side on room.minParticipants - see
// services/competitionService.ts startRoomEarly.
export const startRoomSchema = z.object({
  competitionId: z.string().trim().min(1),
  participantId: z.string().trim().min(1),
  participantToken: z.string().trim().min(1),
});
