export type ExerciseMode = "reps" | "hold";
export type ExerciseCategory =
  | "upper_body"
  | "lower_body"
  | "core"
  | "cardio"
  | "mobility"
  | "full_body";

export interface ExerciseConfig {
  id: string; // matches the URL route param
  name: string;
  tagline: string;
  category: ExerciseCategory;
  mode: ExerciseMode;
  wsRoute: string; // e.g. "/ws/pushup" — the backend WebSocket path
  defaultTarget: number; // reps or seconds depending on mode
  defaultSets: number;
  defaultRestSeconds: number;
  difficulty: "beginner" | "intermediate" | "advanced";
  setupTip: string;
  cameraMirror?: boolean;
  imageUrl?: string; // optional exercise illustration URL the user will provide
}

export const exercises: ExerciseConfig[] = [
  // Upper Body (reps)
  {
    id: "pushup",
    name: "Push-Up",
    wsRoute: "/ws/pushup",
    mode: "reps",
    defaultTarget: 10,
    defaultSets: 3,
    defaultRestSeconds: 45,
    difficulty: "beginner",
    tagline: "Classic upper body staple",
    category: "upper_body",
    setupTip: "Start in high plank, hands shoulder-width, body straight.",
    cameraMirror: true,
    imageUrl:
      "https://t4.ftcdn.net/jpg/03/69/46/35/360_F_369463545_HJgmj8H1l091SWWF3fCHI9jDI6MxSRKZ.jpg",
  },
  {
    id: "bicep_curl_both",
    name: "Bicep Curl (Both Arms)",
    wsRoute: "/ws/bicep_curl_both_arm",
    mode: "reps",
    defaultTarget: 10,
    defaultSets: 3,
    defaultRestSeconds: 45,
    difficulty: "beginner",
    tagline: "Build peak arm strength",
    category: "upper_body",
    setupTip: "Stand tall, curl both arms together keeping elbows fixed.",
    cameraMirror: true,
    imageUrl:
      "https://mrwallpaper.com/images/hd/power-in-every-curl-muscular-man-flexing-biceps-zpn40ycyn9f7rf4j.jpg",
  },
  {
    id: "shoulder_press",
    name: "Shoulder Press",
    wsRoute: "/ws/shoulder_press",
    mode: "reps",
    defaultTarget: 10,
    defaultSets: 3,
    defaultRestSeconds: 60,
    difficulty: "intermediate",
    tagline: "Press overhead for shoulder strength",
    category: "upper_body",
    setupTip: "Start with weights at shoulder height, press fully overhead.",
    cameraMirror: true,
    imageUrl:
      "https://t4.ftcdn.net/jpg/01/42/13/53/360_F_142135317_jGSJW9FTsulJRUzQRtMtMdEJcXJWuMIT.jpg",
  },
  {
    id: "lateral_raise",
    name: "Lateral Raise",
    wsRoute: "/ws/lateral_raise",
    mode: "reps",
    defaultTarget: 10,
    defaultSets: 3,
    defaultRestSeconds: 45,
    difficulty: "beginner",
    tagline: "Sculpt lateral shoulder deltoids",
    category: "upper_body",
    setupTip: "Raise arms sideways to shoulder height, slight elbow bend.",
    cameraMirror: true,
    imageUrl:
      "https://media.istockphoto.com/id/2155499046/photo/young-muscular-man-doing-dumbbell-lateral-raise-exercise-at-gym.jpg?s=612x612&w=0&k=20&c=kAgbNo4a3GiOZbYvUxFf1pmE5JWcsDXm7ktDDeZvrLI=",
  },
  {
    id: "pike_pushup",
    name: "Pike Push-Up",
    wsRoute: "/ws/pike_pushup",
    mode: "reps",
    defaultTarget: 10,
    defaultSets: 3,
    defaultRestSeconds: 45,
    difficulty: "intermediate",
    tagline: "Shoulder-focused push-up variation",
    category: "upper_body",
    setupTip: "Form inverted V, lower head toward ground keeping hips high.",
    cameraMirror: true,
    imageUrl:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSiGGjGMXpUb-o4Vpj7aFCoCDHSCCkF7WdiI-LsV5u_vA&s=10",
  },
  {
    id: "arnold_press",
    name: "Arnold Press",
    wsRoute: "/ws/arnold_press",
    mode: "reps",
    defaultTarget: 10,
    defaultSets: 3,
    defaultRestSeconds: 60,
    difficulty: "intermediate",
    tagline: "Full shoulder rotation press",
    category: "upper_body",
    setupTip: "Rotate palms in as you lower, rotate out as you press up.",
    cameraMirror: true,
    imageUrl:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQt98kB2UvNIYw-i_OobTJnDqkPCW_zZymVDeW4HTSaiDw6oZ4XMMeWFnY&s=10",
  },
  {
    id: "bent_over_row",
    name: "Bent Over Row",
    wsRoute: "/ws/bent_over_row",
    mode: "reps",
    defaultTarget: 10,
    defaultSets: 3,
    defaultRestSeconds: 60,
    difficulty: "intermediate",
    tagline: "Back and bicep compound pull",
    category: "upper_body",
    setupTip:
      "Hinge at hips, pull elbows back past torso, squeeze shoulder blades.",
    cameraMirror: true,
    imageUrl:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR8kxpppwqVIo3Z9oJtUN4JEL4WrD1Z4_YhQU_uowpfAa0ICcyoTEd7lJfp&s=10",
  },
  {
    id: "muay_thai_jab",
    name: "Muay Thai Jab",
    wsRoute: "/ws/muay_thai_jab",
    mode: "reps",
    defaultTarget: 20,
    defaultSets: 3,
    defaultRestSeconds: 30,
    difficulty: "beginner",
    tagline: "Explosive combat conditioning",
    category: "upper_body",
    setupTip: "Guard position, extend lead hand in straight punch, rotate hip.",
    cameraMirror: true,
    imageUrl:
      "https://media.istockphoto.com/id/483095693/photo/boxer-throwing-jab.jpg?s=612x612&w=0&k=20&c=QpTixa3_VxSPJ2OcT8U32zYh3Q0GYGXTDHwdE8PoxUE=",
  },

  // Lower Body (reps)
  {
    id: "squat",
    name: "Squat",
    wsRoute: "/ws/squat",
    mode: "reps",
    defaultTarget: 10,
    defaultSets: 3,
    defaultRestSeconds: 60,
    difficulty: "beginner",
    tagline: "King of lower body exercises",
    category: "lower_body",
    setupTip: "Feet shoulder-width, chest up, knees track over toes.",
    cameraMirror: true,
    imageUrl:
      "https://static.vecteezy.com/system/resources/thumbnails/065/837/362/small/muscular-black-man-performing-a-squat-exercise-against-a-neutral-backdrop-photo.jpeg",
  },
  {
    id: "lunge",
    name: "Lunge",
    wsRoute: "/ws/lunge",
    mode: "reps",
    defaultTarget: 10,
    defaultSets: 3,
    defaultRestSeconds: 45,
    difficulty: "beginner",
    tagline: "Unilateral leg strength & balance",
    category: "lower_body",
    setupTip: "Step forward, lower back knee toward floor, front knee at 90°.",
    cameraMirror: true,
    imageUrl:
      "https://media.istockphoto.com/id/643255584/photo/happy-male-athlete-exercising-lunges-on-the-city-street.jpg?s=612x612&w=0&k=20&c=y59mkebuQx4UjO1ZGtiJ9udGfenggOy8sWgrLeITGuU=",
  },
  {
    id: "sumo_squat",
    name: "Sumo Squat",
    wsRoute: "/ws/sumo_squat",
    mode: "reps",
    defaultTarget: 10,
    defaultSets: 3,
    defaultRestSeconds: 60,
    difficulty: "beginner",
    tagline: "Wide stance inner thigh focus",
    category: "lower_body",
    setupTip: "Wide stance, toes out, squat between legs keeping chest up.",
    cameraMirror: true,
    imageUrl:
      "https://www.gymshark.com/_next/image?url=https%3A%2F%2Fimages.ctfassets.net%2F8urtyqugdt2l%2F6qcnhbUsmIYkzsJZEeqhLD%2F7e63c0c86c1b3540e985dd71f5689499%2Fmobile-sumo-squats_.jpg&w=3840&q=85",
  },
  {
    id: "calf_raise",
    name: "Calf Raise",
    wsRoute: "/ws/calf_raise",
    mode: "reps",
    defaultTarget: 15,
    defaultSets: 3,
    defaultRestSeconds: 30,
    difficulty: "beginner",
    tagline: "Build powerful lower legs",
    category: "lower_body",
    setupTip: "Rise up on toes fully, hold briefly at top, lower slowly.",
    cameraMirror: true,
    imageUrl:
      "https://media.istockphoto.com/id/1202786878/photo/trained-legs-with-muscular-calves-in-sneakers-in-training-gym-during-hard-fitness-and-gym.jpg?s=612x612&w=0&k=20&c=cA1KyWUO-e3-fyk_N1z3ZapoDr2qMPaIK1PlCOK8wbI=",
  },
  {
    id: "single_leg_squat",
    name: "Single Leg Squat",
    wsRoute: "/ws/single_leg_squat",
    mode: "reps",
    defaultTarget: 8,
    defaultSets: 3,
    defaultRestSeconds: 60,
    difficulty: "advanced",
    tagline: "Balance and unilateral strength",
    category: "lower_body",
    setupTip: "Stand on one leg, lower into squat, keep standing heel flat.",
    cameraMirror: true,
    imageUrl:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBAa13XWEHeVYrFIU0DpzTleYBwLdiFNNVCxKVq90WkVDIj1iYlKqW5fgG&s=10",
  },

  // Lower Body (hold)
  {
    id: "bridge_hold",
    name: "Bridge Hold",
    wsRoute: "/ws/bridge_hold",
    mode: "hold",
    defaultTarget: 30,
    defaultSets: 3,
    defaultRestSeconds: 45,
    difficulty: "beginner",
    tagline: "Glute activation and hip stability",
    category: "lower_body",
    setupTip: "Lie on back, feet flat, drive hips up and squeeze glutes.",
    cameraMirror: true,
    imageUrl:
      "https://media.istockphoto.com/id/1419467318/photo/sporty-young-man-training-yoga-over-a-white-background.jpg?s=612x612&w=0&k=20&c=TQaDk3THsyhyMRnkITrbHzs4Sb6f29Ur0Givb01z5Jw=",
  },
  {
    id: "advanced_bridge",
    name: "Advanced Bridge",
    wsRoute: "/ws/advanced_bridge_pose",
    mode: "hold",
    defaultTarget: 20,
    defaultSets: 3,
    defaultRestSeconds: 60,
    difficulty: "advanced",
    tagline: "Full posterior chain activation",
    category: "lower_body",
    setupTip: "Standard bridge then extend one leg, hold hips level.",
    cameraMirror: true,
    imageUrl:
      "https://media.istockphoto.com/id/531050998/photo/variation-of-bridge-pose.jpg?s=612x612&w=0&k=20&c=TviToH1IQFrZ4I2zs2LaJdh609a0fiHfoMk-bB9ChBU=",
  },
  {
    id: "wall_sit",
    name: "Wall Sit",
    wsRoute: "/ws/wall_sit",
    mode: "hold",
    defaultTarget: 30,
    defaultSets: 3,
    defaultRestSeconds: 60,
    difficulty: "beginner",
    tagline: "Isometric quad endurance",
    category: "lower_body",
    setupTip: "Back flat on wall, thighs parallel to floor, knees at 90°.",
    cameraMirror: true,
    imageUrl: "",
  },
  {
    id: "chair_pose",
    name: "Chair Pose",
    wsRoute: "/ws/chair_pose",
    mode: "hold",
    defaultTarget: 20,
    defaultSets: 3,
    defaultRestSeconds: 45,
    difficulty: "beginner",
    tagline: "Yoga squat isometric hold",
    category: "lower_body",
    setupTip: "Feet together, sit back as if into a chair, arms overhead.",
    cameraMirror: true,
    imageUrl: "",
  },

  // Core (reps)
  {
    id: "bicycle_crunch",
    name: "Bicycle Crunch",
    wsRoute: "/ws/bicycle_crunch",
    mode: "reps",
    defaultTarget: 20,
    defaultSets: 3,
    defaultRestSeconds: 30,
    difficulty: "intermediate",
    tagline: "Rotating core power",
    category: "core",
    setupTip: "Alternate elbow to opposite knee in controlled rotation.",
    cameraMirror: true,
    imageUrl: "",
  },
  {
    id: "bird_dog",
    name: "Bird Dog",
    wsRoute: "/ws/bird_dog",
    mode: "reps",
    defaultTarget: 10,
    defaultSets: 3,
    defaultRestSeconds: 30,
    difficulty: "beginner",
    tagline: "Core stability and balance",
    category: "core",
    setupTip: "On all fours, extend opposite arm and leg, keep back flat.",
    cameraMirror: true,
    imageUrl: "",
  },
  {
    id: "dead_bug",
    name: "Dead Bug",
    wsRoute: "/ws/dead_bug",
    mode: "reps",
    defaultTarget: 10,
    defaultSets: 3,
    defaultRestSeconds: 30,
    difficulty: "beginner",
    tagline: "Anti-extension core control",
    category: "core",
    setupTip: "Lie on back, lower opposite arm and leg slowly toward floor.",
    cameraMirror: true,
    imageUrl: "",
  },
  {
    id: "flutter_kicks",
    name: "Flutter Kicks",
    wsRoute: "/ws/flutter_kicks",
    mode: "reps",
    defaultTarget: 20,
    defaultSets: 3,
    defaultRestSeconds: 30,
    difficulty: "intermediate",
    tagline: "Hip flexor and core endurance",
    category: "core",
    setupTip: "Lie flat, legs slightly raised, alternate rapid up-down kicks.",
    cameraMirror: true,
    imageUrl: "",
  },
  {
    id: "leg_raise",
    name: "Leg Raise",
    wsRoute: "/ws/leg_raise",
    mode: "reps",
    defaultTarget: 12,
    defaultSets: 3,
    defaultRestSeconds: 45,
    difficulty: "intermediate",
    tagline: "Lower abs isolation",
    category: "core",
    setupTip:
      "Lie flat, raise both legs to 90° keeping lower back pressed down.",
    cameraMirror: true,
    imageUrl: "",
  },
  {
    id: "russian_twist",
    name: "Russian Twist",
    wsRoute: "/ws/russian_twist",
    mode: "reps",
    defaultTarget: 20,
    defaultSets: 3,
    defaultRestSeconds: 30,
    difficulty: "intermediate",
    tagline: "Oblique rotational strength",
    category: "core",
    setupTip: "Sit at 45°, rotate torso side to side, feet off ground.",
    cameraMirror: true,
    imageUrl: "",
  },

  // Core (hold)
  {
    id: "plank_hold",
    name: "Plank Hold",
    wsRoute: "/ws/plank_hold",
    mode: "hold",
    defaultTarget: 30,
    defaultSets: 3,
    defaultRestSeconds: 45,
    difficulty: "beginner",
    tagline: "Total core stabilization",
    category: "core",
    setupTip: "Forearms on floor, body in straight line, don't let hips drop.",
    cameraMirror: true,
    imageUrl: "",
  },
  {
    id: "side_plank",
    name: "Side Plank",
    wsRoute: "/ws/side_plank",
    mode: "hold",
    defaultTarget: 20,
    defaultSets: 2,
    defaultRestSeconds: 30,
    difficulty: "intermediate",
    tagline: "Lateral core and oblique hold",
    category: "core",
    setupTip: "Stack feet, lift hips into straight line, keep hips high.",
    cameraMirror: true,
    imageUrl: "",
  },
  {
    id: "hollow_hold",
    name: "Hollow Hold",
    wsRoute: "/ws/hollow_hold",
    mode: "hold",
    defaultTarget: 30,
    defaultSets: 3,
    defaultRestSeconds: 45,
    difficulty: "intermediate",
    tagline: "Gymnastic core compression",
    category: "core",
    setupTip: "Lie on back, arms overhead, lift shoulders and legs slightly.",
    cameraMirror: true,
    imageUrl: "",
  },

  // Cardio (reps)
  {
    id: "jumping_jack",
    name: "Jumping Jack",
    wsRoute: "/ws/jumping-jack",
    mode: "reps",
    defaultTarget: 20,
    defaultSets: 3,
    defaultRestSeconds: 30,
    difficulty: "beginner",
    tagline: "Classic full-body cardio",
    category: "cardio",
    setupTip: "Jump feet wide and arms up simultaneously, then return.",
    cameraMirror: true,
    imageUrl: "",
  },
  {
    id: "high_knees",
    name: "High Knees",
    wsRoute: "/ws/high_knees",
    mode: "reps",
    defaultTarget: 20,
    defaultSets: 3,
    defaultRestSeconds: 30,
    difficulty: "beginner",
    tagline: "Running-in-place cardio burst",
    category: "cardio",
    setupTip: "Drive alternating knees up to hip height at a fast pace.",
    cameraMirror: true,
    imageUrl: "",
  },
  {
    id: "mountain_climber",
    name: "Mountain Climber",
    wsRoute: "/ws/mountain_climber",
    mode: "reps",
    defaultTarget: 20,
    defaultSets: 3,
    defaultRestSeconds: 30,
    difficulty: "intermediate",
    tagline: "Full body cardio and core",
    category: "cardio",
    setupTip: "High plank position, alternate driving knees to chest rapidly.",
    cameraMirror: true,
    imageUrl: "",
  },
  {
    id: "butt_kicks",
    name: "Butt Kicks",
    wsRoute: "/ws/butt_kicks",
    mode: "reps",
    defaultTarget: 20,
    defaultSets: 3,
    defaultRestSeconds: 30,
    difficulty: "beginner",
    tagline: "Hamstring activation cardio",
    category: "cardio",
    setupTip: "Jog in place kicking heels up to touch glutes alternately.",
    cameraMirror: true,
    imageUrl: "",
  },
  {
    id: "tuck_jump",
    name: "Tuck Jump",
    wsRoute: "/ws/tuck_jump",
    mode: "reps",
    defaultTarget: 10,
    defaultSets: 3,
    defaultRestSeconds: 60,
    difficulty: "advanced",
    tagline: "Explosive plyometric power",
    category: "cardio",
    setupTip: "Jump and pull both knees to chest, land softly with bent knees.",
    cameraMirror: true,
    imageUrl: "",
  },
  {
    id: "standing_cross_crunch",
    name: "Standing Cross Crunch",
    wsRoute: "/ws/standing_cross_crunch",
    mode: "reps",
    defaultTarget: 10,
    defaultSets: 3,
    defaultRestSeconds: 30,
    difficulty: "beginner",
    tagline: "Standing oblique activation",
    category: "cardio",
    setupTip: "Bring elbow and opposite knee together in standing crunch.",
    cameraMirror: true,
    imageUrl: "",
  },

  // Full Body (reps)
  {
    id: "hindu_pushup",
    name: "Hindu Push-Up",
    wsRoute: "/ws/hindu_pushup",
    mode: "reps",
    defaultTarget: 10,
    defaultSets: 3,
    defaultRestSeconds: 60,
    difficulty: "advanced",
    tagline: "Flowing full body strength",
    category: "full_body",
    setupTip: "Start in downward dog, dive forward into upward dog, reverse.",
    cameraMirror: true,
    imageUrl: "",
  },
  {
    id: "inchworm",
    name: "Inchworm",
    wsRoute: "/ws/inchworm",
    mode: "reps",
    defaultTarget: 10,
    defaultSets: 3,
    defaultRestSeconds: 45,
    difficulty: "intermediate",
    tagline: "Full body mobility and control",
    category: "full_body",
    setupTip: "Hinge forward, walk hands out to plank, walk back up, stand.",
    cameraMirror: true,
    imageUrl: "",
  },
  {
    id: "skandha_chakra",
    name: "Skandha Chakra",
    wsRoute: "/ws/skandha_chakra",
    mode: "reps",
    defaultTarget: 10,
    defaultSets: 3,
    defaultRestSeconds: 30,
    difficulty: "beginner",
    tagline: "Shoulder rotation mobility",
    category: "full_body",
    setupTip: "Rotate shoulders in wide circular motion, both directions.",
    cameraMirror: true,
    imageUrl: "",
  },
  {
    id: "arm_circles",
    name: "Arm Circles",
    wsRoute: "/ws/arm_circles",
    mode: "reps",
    defaultTarget: 10,
    defaultSets: 2,
    defaultRestSeconds: 20,
    difficulty: "beginner",
    tagline: "Shoulder warm-up and mobility",
    category: "mobility",
    setupTip: "Extend arms sideways, rotate in controlled circles.",
    cameraMirror: true,
    imageUrl: "",
  },

  // Full Body (hold)
  {
    id: "superman",
    name: "Superman Hold",
    wsRoute: "/ws/superman",
    mode: "hold",
    defaultTarget: 20,
    defaultSets: 3,
    defaultRestSeconds: 45,
    difficulty: "beginner",
    tagline: "Lower back and posterior chain",
    category: "full_body",
    setupTip:
      "Lie face down, simultaneously lift arms, chest and legs off floor.",
    cameraMirror: true,
    imageUrl: "",
  },

  // Mobility / Yoga (hold)
  {
    id: "tree_pose",
    name: "Tree Pose",
    wsRoute: "/ws/tree_pose",
    mode: "hold",
    defaultTarget: 20,
    defaultSets: 2,
    defaultRestSeconds: 30,
    difficulty: "beginner",
    tagline: "Balance and single-leg stability",
    category: "mobility",
    setupTip: "Stand on one leg, press foot to inner thigh, arms overhead.",
    cameraMirror: true,
    imageUrl: "",
  },
  {
    id: "warrior_ii",
    name: "Warrior II",
    wsRoute: "/ws/warrior_ii",
    mode: "hold",
    defaultTarget: 20,
    defaultSets: 2,
    defaultRestSeconds: 30,
    difficulty: "beginner",
    tagline: "Yoga lower body and hip opening",
    category: "mobility",
    setupTip: "Wide lunge stance, arms extended, gaze over front hand.",
    cameraMirror: true,
    imageUrl: "",
  },
  {
    id: "cobra_pose",
    name: "Cobra Pose",
    wsRoute: "/ws/cobra_pose",
    mode: "hold",
    defaultTarget: 20,
    defaultSets: 2,
    defaultRestSeconds: 30,
    difficulty: "beginner",
    tagline: "Spinal extension and chest opener",
    category: "mobility",
    setupTip:
      "Lie prone, press hands under shoulders, lift chest, elbows soft.",
    cameraMirror: true,
    imageUrl: "",
  },
  {
    id: "downward_dog",
    name: "Downward Dog",
    wsRoute: "/ws/downward_dog",
    mode: "hold",
    defaultTarget: 30,
    defaultSets: 2,
    defaultRestSeconds: 30,
    difficulty: "beginner",
    tagline: "Full posterior chain stretch",
    category: "mobility",
    setupTip: "Inverted V shape, press heels toward floor, shoulders open.",
    cameraMirror: true,
    imageUrl: "",
  },
  {
    id: "dancer_pose",
    name: "Dancer Pose",
    wsRoute: "/ws/dancer_pose",
    mode: "hold",
    defaultTarget: 15,
    defaultSets: 2,
    defaultRestSeconds: 30,
    difficulty: "advanced",
    tagline: "Balance, strength and flexibility",
    category: "mobility",
    setupTip: "Stand on one leg, hold back foot, extend arm and leg back.",
    cameraMirror: true,
    imageUrl: "",
  },
  {
    id: "triangle_pose",
    name: "Triangle Pose",
    wsRoute: "/ws/triangle_pose",
    mode: "hold",
    defaultTarget: 20,
    defaultSets: 2,
    defaultRestSeconds: 30,
    difficulty: "beginner",
    tagline: "Lateral stretch and hip opening",
    category: "mobility",
    setupTip: "Wide stance, reach forward hand down to shin, top arm up.",
    cameraMirror: true,
    imageUrl: "",
  },
  {
    id: "peacock_pose",
    name: "Peacock Pose",
    wsRoute: "/ws/peacock_pose",
    mode: "hold",
    defaultTarget: 15,
    defaultSets: 2,
    defaultRestSeconds: 45,
    difficulty: "advanced",
    tagline: "Wrist and core balance hold",
    category: "mobility",
    setupTip: "Balance body on both hands placed together under abdomen.",
    cameraMirror: true,
    imageUrl: "",
  },
  {
    id: "half_moon",
    name: "Half Moon",
    wsRoute: "/ws/half_moon",
    mode: "hold",
    defaultTarget: 20,
    defaultSets: 2,
    defaultRestSeconds: 30,
    difficulty: "intermediate",
    tagline: "One-leg balance and hip open",
    category: "mobility",
    setupTip: "Balance on one leg, raise other leg parallel, top arm up.",
    cameraMirror: true,
    imageUrl: "",
  },
  {
    id: "reverse_warrior",
    name: "Reverse Warrior",
    wsRoute: "/ws/reverse_warrior",
    mode: "hold",
    defaultTarget: 20,
    defaultSets: 2,
    defaultRestSeconds: 30,
    difficulty: "beginner",
    tagline: "Side body stretch in warrior",
    category: "mobility",
    setupTip: "From Warrior II, lower back arm to back leg, lift front arm up.",
    cameraMirror: true,
    imageUrl: "",
  },
  {
    id: "standing_forward_fold",
    name: "Standing Forward Fold",
    wsRoute: "/ws/standing_forward_fold",
    mode: "hold",
    defaultTarget: 20,
    defaultSets: 2,
    defaultRestSeconds: 20,
    difficulty: "beginner",
    tagline: "Hamstring and spine release",
    category: "mobility",
    setupTip: "Feet hip-width, hinge forward from hips, let head hang heavy.",
    cameraMirror: true,
    imageUrl: "",
  },
  {
    id: "childs_pose",
    name: "Child's Pose",
    wsRoute: "/ws/childs_pose",
    mode: "hold",
    defaultTarget: 30,
    defaultSets: 2,
    defaultRestSeconds: 15,
    difficulty: "beginner",
    tagline: "Rest and spinal decompression",
    category: "mobility",
    setupTip: "Kneel, sit back on heels, arms extended forward on mat.",
    cameraMirror: true,
    imageUrl: "",
  },
  {
    id: "shoulder_stand",
    name: "Shoulder Stand",
    wsRoute: "/ws/shoulder_stand",
    mode: "hold",
    defaultTarget: 20,
    defaultSets: 2,
    defaultRestSeconds: 60,
    difficulty: "advanced",
    tagline: "Inverted balance and core strength",
    category: "full_body",
    setupTip: "Lie on back, lift legs and hips, support lower back with hands.",
    cameraMirror: true,
    imageUrl: "",
  },

  // Mobility (reps)
  {
    id: "front_leg_swing",
    name: "Front Leg Swing",
    wsRoute: "/ws/front_leg_swing",
    mode: "reps",
    defaultTarget: 12,
    defaultSets: 2,
    defaultRestSeconds: 20,
    difficulty: "beginner",
    tagline: "Hip flexor dynamic warm-up",
    category: "mobility",
    setupTip: "Hold wall, swing leg forward and back in controlled arc.",
    cameraMirror: true,
    imageUrl: "",
  },
  {
    id: "side_leg_swing",
    name: "Side Leg Swing",
    wsRoute: "/ws/side_leg_swing",
    mode: "reps",
    defaultTarget: 12,
    defaultSets: 2,
    defaultRestSeconds: 20,
    difficulty: "beginner",
    tagline: "Hip abductor dynamic stretch",
    category: "mobility",
    setupTip: "Hold wall, swing leg side to side across body.",
    cameraMirror: true,
    imageUrl: "",
  },
  {
    id: "windmill",
    name: "Windmill Rotation",
    wsRoute: "/ws/windmill",
    mode: "reps",
    defaultTarget: 10,
    defaultSets: 2,
    defaultRestSeconds: 20,
    difficulty: "beginner",
    tagline: "Thoracic spine rotation",
    category: "mobility",
    setupTip: "Wide stance, rotate upper body touching opposite hand to foot.",
    cameraMirror: true,
    imageUrl: "",
  },
];

export function getExerciseById(id: string): ExerciseConfig | undefined {
  return exercises.find((e) => e.id === id);
}
