export type ExerciseMode = "reps" | "hold";
export type ExerciseCategory =
  | "upper_body"
  | "lower_body"
  | "core"
  | "cardio"
  | "mobility"
  | "full_body";

export interface ExerciseConfig {
  id: string; // matches the URL route param
  name: string;
  tagline: string;
  category: ExerciseCategory;
  mode: ExerciseMode;
  wsRoute: string; // e.g. "/ws/pushup" — the backend WebSocket path
  defaultTarget: number; // reps or seconds depending on mode
  defaultSets: number;
  defaultRestSeconds: number;
  difficulty: "beginner" | "intermediate" | "advanced";
  setupTip: string;
  cameraMirror?: boolean;
  imageUrl?: string; // optional exercise illustration URL the user will provide
}

export const exercises: ExerciseConfig[] = [
  // Upper Body (reps)
  {
    id: "pushup",
    name: "Push-Up",
    wsRoute: "/ws/pushup",
    mode: "reps",
    defaultTarget: 10,
    defaultSets: 3,
    defaultRestSeconds: 45,
    difficulty: "beginner",
    tagline: "Classic upper body staple",
    category: "upper_body",
    setupTip: "Start in high plank, hands shoulder-width, body straight.",
    cameraMirror: true,
    imageUrl:
      "https://t4.ftcdn.net/jpg/03/69/46/35/360_F_369463545_HJgmj8H1l091SWWF3fCHI9jDI6MxSRKZ.jpg",
  },
  {
    id: "bicep_curl_both",
    name: "Bicep Curl (Both Arms)",
    wsRoute: "/ws/bicep_curl_both_arm",
    mode: "reps",
    defaultTarget: 10,
    defaultSets: 3,
    defaultRestSeconds: 45,
    difficulty: "beginner",
    tagline: "Build peak arm strength",
    category: "upper_body",
    setupTip: "Stand tall, curl both arms together keeping elbows fixed.",
    cameraMirror: true,
    imageUrl:
      "https://mrwallpaper.com/images/hd/power-in-every-curl-muscular-man-flexing-biceps-zpn40ycyn9f7rf4j.jpg",
  },
  {
    id: "shoulder_press",
    name: "Shoulder Press",
    wsRoute: "/ws/shoulder_press",
    mode: "reps",
    defaultTarget: 10,
    defaultSets: 3,
    defaultRestSeconds: 60,
    difficulty: "intermediate",
    tagline: "Press overhead for shoulder strength",
    category: "upper_body",
    setupTip: "Start with weights at shoulder height, press fully overhead.",
    cameraMirror: true,
    imageUrl:
      "https://t4.ftcdn.net/jpg/01/42/13/53/360_F_142135317_jGSJW9FTsulJRUzQRtMtMdEJcXJWuMIT.jpg",
  },
  {
    id: "lateral_raise",
    name: "Lateral Raise",
    wsRoute: "/ws/lateral_raise",
    mode: "reps",
    defaultTarget: 10,
    defaultSets: 3,
    defaultRestSeconds: 45,
    difficulty: "beginner",
    tagline: "Sculpt lateral shoulder deltoids",
    category: "upper_body",
    setupTip: "Raise arms sideways to shoulder height, slight elbow bend.",
    cameraMirror: true,
    imageUrl:
      "https://media.istockphoto.com/id/2155499046/photo/young-muscular-man-doing-dumbbell-lateral-raise-exercise-at-gym.jpg?s=612x612&w=0&k=20&c=kAgbNo4a3GiOZbYvUxFf1pmE5JWcsDXm7ktDDeZvrLI=",
  },
  {
    id: "pike_pushup",
    name: "Pike Push-Up",
    wsRoute: "/ws/pike_pushup",
    mode: "reps",
    defaultTarget: 10,
    defaultSets: 3,
    defaultRestSeconds: 45,
    difficulty: "intermediate",
    tagline: "Shoulder-focused push-up variation",
    category: "upper_body",
    setupTip: "Form inverted V, lower head toward ground keeping hips high.",
    cameraMirror: true,
    imageUrl:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSiGGjGMXpUb-o4Vpj7aFCoCDHSCCkF7WdiI-LsV5u_vA&s=10",
  },
  {
    id: "arnold_press",
    name: "Arnold Press",
    wsRoute: "/ws/arnold_press",
    mode: "reps",
    defaultTarget: 10,
    defaultSets: 3,
    defaultRestSeconds: 60,
    difficulty: "intermediate",
    tagline: "Full shoulder rotation press",
    category: "upper_body",
    setupTip: "Rotate palms in as you lower, rotate out as you press up.",
    cameraMirror: true,
    imageUrl:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQt98kB2UvNIYw-i_OobTJnDqkPCW_zZymVDeW4HTSaiDw6oZ4XMMeWFnY&s=10",
  },
  {
    id: "bent_over_row",
    name: "Bent Over Row",
    wsRoute: "/ws/bent_over_row",
    mode: "reps",
    defaultTarget: 10,
    defaultSets: 3,
    defaultRestSeconds: 60,
    difficulty: "intermediate",
    tagline: "Back and bicep compound pull",
    category: "upper_body",
    setupTip:
      "Hinge at hips, pull elbows back past torso, squeeze shoulder blades.",
    cameraMirror: true,
    imageUrl:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR8kxpppwqVIo3Z9oJtUN4JEL4WrD1Z4_YhQU_uowpfAa0ICcyoTEd7lJfp&s=10",
  },
  {
    id: "muay_thai_jab",
    name: "Muay Thai Jab",
    wsRoute: "/ws/muay_thai_jab",
    mode: "reps",
    defaultTarget: 20,
    defaultSets: 3,
    defaultRestSeconds: 30,
    difficulty: "beginner",
    tagline: "Explosive combat conditioning",
    category: "upper_body",
    setupTip: "Guard position, extend lead hand in straight punch, rotate hip.",
    cameraMirror: true,
    imageUrl:
      "https://media.istockphoto.com/id/483095693/photo/boxer-throwing-jab.jpg?s=612x612&w=0&k=20&c=QpTixa3_VxSPJ2OcT8U32zYh3Q0GYGXTDHwdE8PoxUE=",
  },

  // Lower Body (reps)
  {
    id: "squat",
    name: "Squat",
    wsRoute: "/ws/squat",
    mode: "reps",
    defaultTarget: 10,
    defaultSets: 3,
    defaultRestSeconds: 60,
    difficulty: "beginner",
    tagline: "King of lower body exercises",
    category: "lower_body",
    setupTip: "Feet shoulder-width, chest up, knees track over toes.",
    cameraMirror: true,
    imageUrl:
      "https://static.vecteezy.com/system/resources/thumbnails/065/837/362/small/muscular-black-man-performing-a-squat-exercise-against-a-neutral-backdrop-photo.jpeg",
  },
  {
    id: "lunge",
    name: "Lunge",
    wsRoute: "/ws/lunge",
    mode: "reps",
    defaultTarget: 10,
    defaultSets: 3,
    defaultRestSeconds: 45,
    difficulty: "beginner",
    tagline: "Unilateral leg strength & balance",
    category: "lower_body",
    setupTip: "Step forward, lower back knee toward floor, front knee at 90°.",
    cameraMirror: true,
    imageUrl:
      "https://media.istockphoto.com/id/643255584/photo/happy-male-athlete-exercising-lunges-on-the-city-street.jpg?s=612x612&w=0&k=20&c=y59mkebuQx4UjO1ZGtiJ9udGfenggOy8sWgrLeITGuU=",
  },
  {
    id: "sumo_squat",
    name: "Sumo Squat",
    wsRoute: "/ws/sumo_squat",
    mode: "reps",
    defaultTarget: 10,
    defaultSets: 3,
    defaultRestSeconds: 60,
    difficulty: "beginner",
    tagline: "Wide stance inner thigh focus",
    category: "lower_body",
    setupTip: "Wide stance, toes out, squat between legs keeping chest up.",
    cameraMirror: true,
    imageUrl:
      "https://www.gymshark.com/_next/image?url=https%3A%2F%2Fimages.ctfassets.net%2F8urtyqugdt2l%2F6qcnhbUsmIYkzsJZEeqhLD%2F7e63c0c86c1b3540e985dd71f5689499%2Fmobile-sumo-squats_.jpg&w=3840&q=85",
  },
  {
    id: "calf_raise",
    name: "Calf Raise",
    wsRoute: "/ws/calf_raise",
    mode: "reps",
    defaultTarget: 15,
    defaultSets: 3,
    defaultRestSeconds: 30,
    difficulty: "beginner",
    tagline: "Build powerful lower legs",
    category: "lower_body",
    setupTip: "Rise up on toes fully, hold briefly at top, lower slowly.",
    cameraMirror: true,
    imageUrl:
      "https://media.istockphoto.com/id/1202786878/photo/trained-legs-with-muscular-calves-in-sneakers-in-training-gym-during-hard-fitness-and-gym.jpg?s=612x612&w=0&k=20&c=cA1KyWUO-e3-fyk_N1z3ZapoDr2qMPaIK1PlCOK8wbI=",
  },
  {
    id: "single_leg_squat",
    name: "Single Leg Squat",
    wsRoute: "/ws/single_leg_squat",
    mode: "reps",
    defaultTarget: 8,
    defaultSets: 3,
    defaultRestSeconds: 60,
    difficulty: "advanced",
    tagline: "Balance and unilateral strength",
    category: "lower_body",
    setupTip: "Stand on one leg, lower into squat, keep standing heel flat.",
    cameraMirror: true,
    imageUrl:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBAa13XWEHeVYrFIU0DpzTleYBwLdiFNNVCxKVq90WkVDIj1iYlKqW5fgG&s=10",
  },

  // Lower Body (hold)
  {
    id: "bridge_hold",
    name: "Bridge Hold",
    wsRoute: "/ws/bridge_hold",
    mode: "hold",
    defaultTarget: 30,
    defaultSets: 3,
    defaultRestSeconds: 45,
    difficulty: "beginner",
    tagline: "Glute activation and hip stability",
    category: "lower_body",
    setupTip: "Lie on back, feet flat, drive hips up and squeeze glutes.",
    cameraMirror: true,
    imageUrl:
      "https://media.istockphoto.com/id/1419467318/photo/sporty-young-man-training-yoga-over-a-white-background.jpg?s=612x612&w=0&k=20&c=TQaDk3THsyhyMRnkITrbHzs4Sb6f29Ur0Givb01z5Jw=",
  },
  {
    id: "advanced_bridge",
    name: "Advanced Bridge",
    wsRoute: "/ws/advanced_bridge_pose",
    mode: "hold",
    defaultTarget: 20,
    defaultSets: 3,
    defaultRestSeconds: 60,
    difficulty: "advanced",
    tagline: "Full posterior chain activation",
    category: "lower_body",
    setupTip: "Standard bridge then extend one leg, hold hips level.",
    cameraMirror: true,
    imageUrl:
      "https://media.istockphoto.com/id/531050998/photo/variation-of-bridge-pose.jpg?s=612x612&w=0&k=20&c=TviToH1IQFrZ4I2zs2LaJdh609a0fiHfoMk-bB9ChBU=",
  },
  {
    id: "wall_sit",
    name: "Wall Sit",
    wsRoute: "/ws/wall_sit",
    mode: "hold",
    defaultTarget: 30,
    defaultSets: 3,
    defaultRestSeconds: 60,
    difficulty: "beginner",
    tagline: "Isometric quad endurance",
    category: "lower_body",
    setupTip: "Back flat on wall, thighs parallel to floor, knees at 90°.",
    cameraMirror: true,
    imageUrl:
      "https://media.istockphoto.com/id/1365425038/photo/young-man-doing-the-wall-sit-exercise-outdoors.jpg?s=612x612&w=0&k=20&c=0etXyX6J6zNnym0cq0w2NjzUtGfKp1GWtdIA7mtZdag=",
  },
  {
    id: "chair_pose",
    name: "Chair Pose",
    wsRoute: "/ws/chair_pose",
    mode: "hold",
    defaultTarget: 20,
    defaultSets: 3,
    defaultRestSeconds: 45,
    difficulty: "beginner",
    tagline: "Yoga squat isometric hold",
    category: "lower_body",
    setupTip: "Feet together, sit back as if into a chair, arms overhead.",
    cameraMirror: true,
    imageUrl:
      "https://media.istockphoto.com/id/1693785644/video/strong-african-muscular-man-in-activewear-practicing-squats-on-mat.jpg?s=640x640&k=20&c=Vq4A7tE9KvZGQX2_PSpkitZen92t9PnXgBxPJezgtns=",
  },

  // Core (reps)
  {
    id: "bicycle_crunch",
    name: "Bicycle Crunch",
    wsRoute: "/ws/bicycle_crunch",
    mode: "reps",
    defaultTarget: 20,
    defaultSets: 3,
    defaultRestSeconds: 30,
    difficulty: "intermediate",
    tagline: "Rotating core power",
    category: "core",
    setupTip: "Alternate elbow to opposite knee in controlled rotation.",
    cameraMirror: true,
    imageUrl:
      "https://media.istockphoto.com/id/1288561179/photo/man-exercising-in-living-room.jpg?s=612x612&w=0&k=20&c=49FKPJC-OOGQ1ZB1cv2Rleyi88OpaptZf0heak5nN0M=",
  },
  {
    id: "bird_dog",
    name: "Bird Dog",
    wsRoute: "/ws/bird_dog",
    mode: "reps",
    defaultTarget: 10,
    defaultSets: 3,
    defaultRestSeconds: 30,
    difficulty: "beginner",
    tagline: "Core stability and balance",
    category: "core",
    setupTip: "On all fours, extend opposite arm and leg, keep back flat.",
    cameraMirror: true,
    imageUrl:
      "https://media.istockphoto.com/id/2266523731/photo/young-african-man-doing-bird-dog-pose-at-home.jpg?s=612x612&w=0&k=20&c=ktgfJESAPe3Yrkr6ria42z6nJHNTEEdqH0Uls59mu_E=",
  },
  {
    id: "dead_bug",
    name: "Dead Bug",
    wsRoute: "/ws/dead_bug",
    mode: "reps",
    defaultTarget: 10,
    defaultSets: 3,
    defaultRestSeconds: 30,
    difficulty: "beginner",
    tagline: "Anti-extension core control",
    category: "core",
    setupTip: "Lie on back, lower opposite arm and leg slowly toward floor.",
    cameraMirror: true,
    imageUrl:
      "https://trainingstation.co.uk/cdn/shop/articles/dead-bug-dark-black-skin-tone_85ffd456-9891-4b85-87ed-5fb85961c72d_1248x.png?v=1780253571",
  },
  {
    id: "flutter_kicks",
    name: "Flutter Kicks",
    wsRoute: "/ws/flutter_kicks",
    mode: "reps",
    defaultTarget: 20,
    defaultSets: 3,
    defaultRestSeconds: 30,
    difficulty: "intermediate",
    tagline: "Hip flexor and core endurance",
    category: "core",
    setupTip: "Lie flat, legs slightly raised, alternate rapid up-down kicks.",
    cameraMirror: true,
    imageUrl:
      "https://cache.getarchive.net/Prod/thumb/cdn2/L3Bob3RvLzIwMTgvMDcvMzAvZmx1dHRlci1raWNrcy1hcmUtYS10eXBlLW9mLWFiZG9taW5hbC13b3Jrb3V0LXRoYXQtMDVmZTRmLTEwMjQuanBn/320/228/jpg",
  },
  {
    id: "leg_raise",
    name: "Leg Raise",
    wsRoute: "/ws/leg_raise",
    mode: "reps",
    defaultTarget: 12,
    defaultSets: 3,
    defaultRestSeconds: 45,
    difficulty: "intermediate",
    tagline: "Lower abs isolation",
    category: "core",
    setupTip:
      "Lie flat, raise both legs to 90° keeping lower back pressed down.",
    cameraMirror: true,
    imageUrl:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRO-1oU22NO4lrqVQvzl0jMKFGbw705jU_KULTnnA-6IHq15i-0ALOgmiVk&s=10",
  },
  {
    id: "russian_twist",
    name: "Russian Twist",
    wsRoute: "/ws/russian_twist",
    mode: "reps",
    defaultTarget: 20,
    defaultSets: 3,
    defaultRestSeconds: 30,
    difficulty: "intermediate",
    tagline: "Oblique rotational strength",
    category: "core",
    setupTip: "Sit at 45°, rotate torso side to side, feet off ground.",
    cameraMirror: true,
    imageUrl:
      "https://www.themanual.com/tachyon/sites/9/2020/12/ab-workout-medicine-ball-russian-twist-e1741878022454.jpg?fit=1500%2C900",
  },

  // Core (hold)
  {
    id: "plank_hold",
    name: "Plank Hold",
    wsRoute: "/ws/plank_hold",
    mode: "hold",
    defaultTarget: 30,
    defaultSets: 3,
    defaultRestSeconds: 45,
    difficulty: "beginner",
    tagline: "Total core stabilization",
    category: "core",
    setupTip: "Forearms on floor, body in straight line, don't let hips drop.",
    cameraMirror: true,
    imageUrl:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbF38U7zRzIbduE7TZhg5K8FzeXYONDiZqxG1XBwYcQURDFAt0JTHZGZk&s=10",
  },
  {
    id: "side_plank",
    name: "Side Plank",
    wsRoute: "/ws/side_plank",
    mode: "hold",
    defaultTarget: 20,
    defaultSets: 2,
    defaultRestSeconds: 30,
    difficulty: "intermediate",
    tagline: "Lateral core and oblique hold",
    category: "core",
    setupTip: "Stack feet, lift hips into straight line, keep hips high.",
    cameraMirror: true,
    imageUrl:
      "https://media.istockphoto.com/id/1143721932/photo/muscular-athlete-doing-a-sideways-plank-exercise-in-a-gym-gym.jpg?s=612x612&w=0&k=20&c=Vr_TDyDlyEi4v5Mfvx-btLocEsiUdg1YtlULQOZyx6s=",
  },
  {
    id: "hollow_hold",
    name: "Hollow Hold",
    wsRoute: "/ws/hollow_hold",
    mode: "hold",
    defaultTarget: 30,
    defaultSets: 3,
    defaultRestSeconds: 45,
    difficulty: "intermediate",
    tagline: "Gymnastic core compression",
    category: "core",
    setupTip: "Lie on back, arms overhead, lift shoulders and legs slightly.",
    cameraMirror: true,
    imageUrl:
      "https://images.ctfassets.net/6ilvqec50fal/2UwZp8tGL5VUzyAJwWgNVJ/5ed6b3c8a3b6e2feb22db455edc8ea41/hollowbody_andyspeer.png",
  },

  // Cardio (reps)
  {
    id: "jumping_jack",
    name: "Jumping Jack",
    wsRoute: "/ws/jumping-jack",
    mode: "reps",
    defaultTarget: 20,
    defaultSets: 3,
    defaultRestSeconds: 30,
    difficulty: "beginner",
    tagline: "Classic full-body cardio",
    category: "cardio",
    setupTip: "Jump feet wide and arms up simultaneously, then return.",
    cameraMirror: true,
    imageUrl:
      "https://sworkit.com/wp-content/uploads/2020/06/sworkit-jumping-jack.gif",
  },
  {
    id: "high_knees",
    name: "High Knees",
    wsRoute: "/ws/high_knees",
    mode: "reps",
    defaultTarget: 20,
    defaultSets: 3,
    defaultRestSeconds: 30,
    difficulty: "beginner",
    tagline: "Running-in-place cardio burst",
    category: "cardio",
    setupTip: "Drive alternating knees up to hip height at a fast pace.",
    cameraMirror: true,
    imageUrl:
      "https://media.post.rvohealth.io/wp-content/uploads/sites/2/2019/05/RUNNING-DRILLS_HIGH-KNEES_2.gif",
  },
  {
    id: "mountain_climber",
    name: "Mountain Climber",
    wsRoute: "/ws/mountain_climber",
    mode: "reps",
    defaultTarget: 20,
    defaultSets: 3,
    defaultRestSeconds: 30,
    difficulty: "intermediate",
    tagline: "Full body cardio and core",
    category: "cardio",
    setupTip: "High plank position, alternate driving knees to chest rapidly.",
    cameraMirror: true,
    imageUrl:
      "https://media.post.rvohealth.io/wp-content/uploads/sites/2/2019/05/LOWER-ABS_MOUNTAIN-CLIMBERS.gif",
  },
  {
    id: "butt_kicks",
    name: "Butt Kicks",
    wsRoute: "/ws/butt_kicks",
    mode: "reps",
    defaultTarget: 20,
    defaultSets: 3,
    defaultRestSeconds: 30,
    difficulty: "beginner",
    tagline: "Hamstring activation cardio",
    category: "cardio",
    setupTip: "Jog in place kicking heels up to touch glutes alternately.",
    cameraMirror: true,
    imageUrl: "https://i.makeagif.com/media/8-31-2022/PEMH1o.gif",
  },
  {
    id: "tuck_jump",
    name: "Tuck Jump",
    wsRoute: "/ws/tuck_jump",
    mode: "reps",
    defaultTarget: 10,
    defaultSets: 3,
    defaultRestSeconds: 60,
    difficulty: "advanced",
    tagline: "Explosive plyometric power",
    category: "cardio",
    setupTip: "Jump and pull both knees to chest, land softly with bent knees.",
    cameraMirror: true,
    imageUrl:
      "https://i.pinimg.com/originals/7f/2a/de/7f2adee8886b5964e937e0232edee31b.gif",
  },
  {
    id: "standing_cross_crunch",
    name: "Standing Cross Crunch",
    wsRoute: "/ws/standing_cross_crunch",
    mode: "reps",
    defaultTarget: 10,
    defaultSets: 3,
    defaultRestSeconds: 30,
    difficulty: "beginner",
    tagline: "Standing oblique activation",
    category: "cardio",
    setupTip: "Bring elbow and opposite knee together in standing crunch.",
    cameraMirror: true,
    imageUrl:
      "https://www.zing.coach/exercises/standing-elbow-to-knee-crunches.webp",
  },

  // Full Body (reps)
  {
    id: "hindu_pushup",
    name: "Hindu Push-Up",
    wsRoute: "/ws/hindu_pushup",
    mode: "reps",
    defaultTarget: 10,
    defaultSets: 3,
    defaultRestSeconds: 60,
    difficulty: "advanced",
    tagline: "Flowing full body strength",
    category: "full_body",
    setupTip: "Start in downward dog, dive forward into upward dog, reverse.",
    cameraMirror: true,
    imageUrl:
      "https://flabfix.com/wp-content/uploads/2019/06/Hindu-Push-Ups.gif",
  },
  {
    id: "inchworm",
    name: "Inchworm",
    wsRoute: "/ws/inchworm",
    mode: "reps",
    defaultTarget: 10,
    defaultSets: 3,
    defaultRestSeconds: 45,
    difficulty: "intermediate",
    tagline: "Full body mobility and control",
    category: "full_body",
    setupTip: "Hinge forward, walk hands out to plank, walk back up, stand.",
    cameraMirror: true,
    imageUrl:
      "https://downloads.ctfassets.net/6ilvqec50fal/12KWVMr128HkdwjWGZoNfv/371f71339d04795c24edb947a2d5cc86/Untitled_design__22_.gif",
  },
  {
    id: "skandha_chakra",
    name: "Skandha Chakra",
    wsRoute: "/ws/skandha_chakra",
    mode: "reps",
    defaultTarget: 10,
    defaultSets: 3,
    defaultRestSeconds: 30,
    difficulty: "beginner",
    tagline: "Shoulder rotation mobility",
    category: "full_body",
    setupTip: "Rotate shoulders in wide circular motion, both directions.",
    cameraMirror: true,
    imageUrl:
      "https://echo.santulan.in/wp-content/uploads/2022/04/Skanda-Blog-Image-1-1568x882.png",
  },
  {
    id: "arm_circles",
    name: "Arm Circles",
    wsRoute: "/ws/arm_circles",
    mode: "reps",
    defaultTarget: 10,
    defaultSets: 2,
    defaultRestSeconds: 20,
    difficulty: "beginner",
    tagline: "Shoulder warm-up and mobility",
    category: "mobility",
    setupTip: "Extend arms sideways, rotate in controlled circles.",
    cameraMirror: true,
    imageUrl:
      "https://i.pinimg.com/originals/d0/87/8c/d0878cb3d04c3bcfa16774df4dc60dd3.gif",
  },

  // Full Body (hold)
  {
    id: "superman",
    name: "Superman Hold",
    wsRoute: "/ws/superman",
    mode: "hold",
    defaultTarget: 20,
    defaultSets: 3,
    defaultRestSeconds: 45,
    difficulty: "beginner",
    tagline: "Lower back and posterior chain",
    category: "full_body",
    setupTip:
      "Lie face down, simultaneously lift arms, chest and legs off floor.",
    cameraMirror: true,
    imageUrl:
      "https://images.ctfassets.net/hjcv6wdwxsdz/79sS2tpNEIFtGYuBfCNxYi/8367923f934c6f2369f50b3f42c57be8/superman-exercise-hold.png?w=1200",
  },

  // Mobility / Yoga (hold)
  {
    id: "tree_pose",
    name: "Tree Pose",
    wsRoute: "/ws/tree_pose",
    mode: "hold",
    defaultTarget: 20,
    defaultSets: 2,
    defaultRestSeconds: 30,
    difficulty: "beginner",
    tagline: "Balance and single-leg stability",
    category: "mobility",
    setupTip: "Stand on one leg, press foot to inner thigh, arms overhead.",
    cameraMirror: true,
    imageUrl:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRtVLzshz-4uB16hbpJG0WeLjDY_cfoH7chkS5kqeCBwZzNde3_GdQXApg&s=10",
  },
  {
    id: "warrior_ii",
    name: "Warrior II",
    wsRoute: "/ws/warrior_ii",
    mode: "hold",
    defaultTarget: 20,
    defaultSets: 2,
    defaultRestSeconds: 30,
    difficulty: "beginner",
    tagline: "Yoga lower body and hip opening",
    category: "mobility",
    setupTip: "Wide lunge stance, arms extended, gaze over front hand.",
    cameraMirror: true,
    imageUrl:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSxL7hdWnUSz3X2Aw71s_dUg4DOIlC-hJ6gA4T5DLgACHsRcNBIcGCzTZaB&s=10",
  },
  {
    id: "cobra_pose",
    name: "Cobra Pose",
    wsRoute: "/ws/cobra_pose",
    mode: "hold",
    defaultTarget: 20,
    defaultSets: 2,
    defaultRestSeconds: 30,
    difficulty: "beginner",
    tagline: "Spinal extension and chest opener",
    category: "mobility",
    setupTip:
      "Lie prone, press hands under shoulders, lift chest, elbows soft.",
    cameraMirror: true,
    imageUrl:
      "https://cdn.yogajournal.com/wp-content/uploads/2007/08/Cobra-Pose_Andrew-Clark.gif",
  },
  {
    id: "downward_dog",
    name: "Downward Dog",
    wsRoute: "/ws/downward_dog",
    mode: "hold",
    defaultTarget: 30,
    defaultSets: 2,
    defaultRestSeconds: 30,
    difficulty: "beginner",
    tagline: "Full posterior chain stretch",
    category: "mobility",
    setupTip: "Inverted V shape, press heels toward floor, shoulders open.",
    cameraMirror: true,
    imageUrl:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSWdCIHP-LQQVp19Z1jdZ1aE1OnVyUYEToYghP-Kzpp3nqUtUcb8hWQ_k0&s=10",
  },
  {
    id: "dancer_pose",
    name: "Dancer Pose",
    wsRoute: "/ws/dancer_pose",
    mode: "hold",
    defaultTarget: 15,
    defaultSets: 2,
    defaultRestSeconds: 30,
    difficulty: "advanced",
    tagline: "Balance, strength and flexibility",
    category: "mobility",
    setupTip: "Stand on one leg, hold back foot, extend arm and leg back.",
    cameraMirror: true,
    imageUrl:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSBtriRqlWJp-FRDHIu_YQMX6uXbysIFZP5sI7JHw-Tqs5oNitYzF2G8jo&s=10",
  },
  {
    id: "triangle_pose",
    name: "Triangle Pose",
    wsRoute: "/ws/triangle_pose",
    mode: "hold",
    defaultTarget: 20,
    defaultSets: 2,
    defaultRestSeconds: 30,
    difficulty: "beginner",
    tagline: "Lateral stretch and hip opening",
    category: "mobility",
    setupTip: "Wide stance, reach forward hand down to shin, top arm up.",
    cameraMirror: true,
    imageUrl:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRh-bJksr36KcX3viO9KdhPU3UfdL6rqkZr5h3zL9v_-PvPX21GiFZx4Gs&s=10",
  },
  {
    id: "peacock_pose",
    name: "Peacock Pose",
    wsRoute: "/ws/peacock_pose",
    mode: "hold",
    defaultTarget: 15,
    defaultSets: 2,
    defaultRestSeconds: 45,
    difficulty: "advanced",
    tagline: "Wrist and core balance hold",
    category: "mobility",
    setupTip: "Balance body on both hands placed together under abdomen.",
    cameraMirror: true,
    imageUrl:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6E8iDBGuvCsfanC3Q2qNsU3o90QjxpUtvqgkqo0n7Q4uyg-TtjCtmWUQ&s=10",
  },
  {
    id: "half_moon",
    name: "Half Moon",
    wsRoute: "/ws/half_moon",
    mode: "hold",
    defaultTarget: 20,
    defaultSets: 2,
    defaultRestSeconds: 30,
    difficulty: "intermediate",
    tagline: "One-leg balance and hip open",
    category: "mobility",
    setupTip: "Balance on one leg, raise other leg parallel, top arm up.",
    cameraMirror: true,
    imageUrl:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS4_khlLMGgr834ZjpyXVFgtOFw15tUdhe360VyakvTlJscePxaPLhhBXA&s=10",
  },
  {
    id: "reverse_warrior",
    name: "Reverse Warrior",
    wsRoute: "/ws/reverse_warrior",
    mode: "hold",
    defaultTarget: 20,
    defaultSets: 2,
    defaultRestSeconds: 30,
    difficulty: "beginner",
    tagline: "Side body stretch in warrior",
    category: "mobility",
    setupTip: "From Warrior II, lower back arm to back leg, lift front arm up.",
    cameraMirror: true,
    imageUrl:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSR4SOvWgfFZ60vs_S89iqRDCUIw7ZexAFdntnBJ0wyQfHRpRnvIJ39_TR4&s=10",
  },
  {
    id: "standing_forward_fold",
    name: "Standing Forward Fold",
    wsRoute: "/ws/standing_forward_fold",
    mode: "hold",
    defaultTarget: 20,
    defaultSets: 2,
    defaultRestSeconds: 20,
    difficulty: "beginner",
    tagline: "Hamstring and spine release",
    category: "mobility",
    setupTip: "Feet hip-width, hinge forward from hips, let head hang heavy.",
    cameraMirror: true,
    imageUrl:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR0HR1I1bxXAPe41-zPWrcRvvQYP77v6A1Mue01bro4ZA&s=10",
  },
  {
    id: "childs_pose",
    name: "Child's Pose",
    wsRoute: "/ws/childs_pose",
    mode: "hold",
    defaultTarget: 30,
    defaultSets: 2,
    defaultRestSeconds: 15,
    difficulty: "beginner",
    tagline: "Rest and spinal decompression",
    category: "mobility",
    setupTip: "Kneel, sit back on heels, arms extended forward on mat.",
    cameraMirror: true,
    imageUrl:
      "https://www.theyogacollective.com/wp-content/uploads/2019/10/4143473057707883372_IMG_8546-2-e1572149256273.jpg",
  },
  {
    id: "shoulder_stand",
    name: "Shoulder Stand",
    wsRoute: "/ws/shoulder_stand",
    mode: "hold",
    defaultTarget: 20,
    defaultSets: 2,
    defaultRestSeconds: 60,
    difficulty: "advanced",
    tagline: "Inverted balance and core strength",
    category: "full_body",
    setupTip: "Lie on back, lift legs and hips, support lower back with hands.",
    cameraMirror: true,
    imageUrl:
      "https://beyogi.b-cdn.net/wp-content/uploads/2015/03/Shoulderstand-Pose-Sarvangasana.png?width=600&quality=70",
  },

  // Mobility (reps)
  {
    id: "front_leg_swing",
    name: "Front Leg Swing",
    wsRoute: "/ws/front_leg_swing",
    mode: "reps",
    defaultTarget: 12,
    defaultSets: 2,
    defaultRestSeconds: 20,
    difficulty: "beginner",
    tagline: "Hip flexor dynamic warm-up",
    category: "mobility",
    setupTip: "Hold wall, swing leg forward and back in controlled arc.",
    cameraMirror: true,
    imageUrl: "https://i.makeagif.com/media/10-07-2024/gH2w9M.gif",
  },
  {
    id: "side_leg_swing",
    name: "Side Leg Swing",
    wsRoute: "/ws/side_leg_swing",
    mode: "reps",
    defaultTarget: 12,
    defaultSets: 2,
    defaultRestSeconds: 20,
    difficulty: "beginner",
    tagline: "Hip abductor dynamic stretch",
    category: "mobility",
    setupTip: "Hold wall, swing leg side to side across body.",
    cameraMirror: true,
    imageUrl:
      "https://i.pinimg.com/originals/84/d8/44/84d844a7f515f69f2eb05696031d5790.gif",
  },
  {
    id: "windmill",
    name: "Windmill Rotation",
    wsRoute: "/ws/windmill",
    mode: "reps",
    defaultTarget: 10,
    defaultSets: 2,
    defaultRestSeconds: 20,
    difficulty: "beginner",
    tagline: "Thoracic spine rotation",
    category: "mobility",
    setupTip: "Wide stance, rotate upper body touching opposite hand to foot.",
    cameraMirror: true,
    imageUrl:
      "https://www.24hourfitness.com/24life/fitness/2020/media_1cf7da6901d3546f68cf5b6be431983f84a03d816.gif?width=750&format=gif&optimize=medium",
  },
  {
    id: "front_raise",
    name: "Front Raise",
    wsRoute: "/ws/front_raise",
    mode: "reps",
    defaultTarget: 12,
    defaultSets: 3,
    defaultRestSeconds: 45,
    difficulty: "beginner",
    tagline: "Anterior deltoid isolation",
    category: "upper_body",
    setupTip:
      "Stand tall, arms at sides, raise straight arms to shoulder height in front.",
    cameraMirror: true,
    imageUrl:
      "https://i0.wp.com/www.strengthlog.com/wp-content/uploads/2020/03/Dumbbell-Front-Raise.gif?fit=600%2C600&ssl=1",
  },
  {
    id: "seated_cable_shrug",
    name: "Seated Cable Shrug",
    wsRoute: "/ws/seated_cable_shrug",
    mode: "reps",
    defaultTarget: 12,
    defaultSets: 3,
    defaultRestSeconds: 60,
    difficulty: "beginner",
    tagline: "Upper trap elevation with constant tension",
    category: "upper_body",
    setupTip:
      "Sit facing a low-pulley cable with a V-bar or straight bar. Keep arms straight, back tall, and shrug shoulders up toward ears, pause, then lower slowly.",
    cameraMirror: true,
    imageUrl:
      "https://hips.hearstapps.com/hmg-prod/images/766/fitgif9-22-tnoverride-1506088802.gif?crop=1xw:0.884xh;center,top&resize=1200:*",
  },
  {
    id: "tricep_dip",
    name: "Tricep Dip",
    wsRoute: "/ws/tricep_dip",
    mode: "reps",
    defaultTarget: 10,
    defaultSets: 3,
    defaultRestSeconds: 60,
    difficulty: "intermediate",
    tagline: "Compound triceps and shoulder extension",
    category: "upper_body",
    setupTip:
      "Grip parallel bars shoulder-width, keep torso upright, elbows tucked. Lower until upper arms are about parallel to the floor, then press back up.",
    cameraMirror: true,
    imageUrl:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTBHVpdsO4CVFy1lJz-jdX2qFOq_38woukY5OvTowpkirKwfui3FeKcCxc&s=10",
  },
  {
    id: "standing_trunk_rotation",
    name: "Standing Trunk Rotation",
    wsRoute: "/ws/standing_trunk_rotation",
    mode: "reps",
    defaultTarget: 10,
    defaultSets: 2,
    defaultRestSeconds: 20,
    difficulty: "beginner",
    tagline: "Controlled thoracic rotation",
    category: "upper_body",
    setupTip:
      "Feet hip-width, arms bent 90° or straight in front, rotate upper body left and right while keeping hips stable.",
    cameraMirror: true,
    imageUrl:
      "https://www.bhf.org.uk/-/media/images/information-support/heart-matters/2024/feb-2024/activity/exercises-for-lower-back-pain/14_standingtrunkrotation_1x1_v2.gif?rev=e4df5cf9870f45cab757ef5baadaf38d&hash=5410AADDF7B955DF27A971D989A7F002",
  },
  {
    id: "single_arm_cable_lateral_raise_crossbody",
    name: "Single Arm Cable Lateral Raise (Crossbody)",
    wsRoute: "/ws/single_arm_cable_lateral_raise_crossbody",
    mode: "reps",
    defaultTarget: 12,
    defaultSets: 3,
    defaultRestSeconds: 45,
    difficulty: "beginner",
    tagline: "Lateral deltoid isolation with constant tension",
    category: "upper_body",
    setupTip:
      "Set cable to lowest position, stand sideways, reach across body with far hand, slight elbow bend, raise arm out to side until ~shoulder height, then lower under control.",
    cameraMirror: true,
    imageUrl:
      "https://cdn.muscleandstrength.com/sites/default/files/single-arm-cable-lateral-raise.jpg",
  },
  {
    id: "cable_upright_row",
    name: "Cable Upright Row",
    wsRoute: "/ws/cable_upright_row",
    mode: "reps",
    defaultTarget: 12,
    defaultSets: 3,
    defaultRestSeconds: 60,
    difficulty: "beginner",
    tagline: "Lateral delts and upper traps with constant tension",
    category: "upper_body",
    setupTip:
      "Attach a straight bar or rope to a low pulley. Stand tall, grip with hands shoulder-width or slightly narrower, pull the bar up along your body by leading with elbows until they reach ~shoulder height, then lower under control.",
    cameraMirror: true,
    imageUrl:
      "https://cdn.muscleandstrength.com/sites/default/files/cable-upright-row-1.jpg",
  },
  {
    id: "dumbbell_pull_over",
    name: "Dumbbell Pull Over",
    wsRoute: "/ws/dumbbell_pull_over",
    mode: "reps",
    defaultTarget: 10,
    defaultSets: 3,
    defaultRestSeconds: 60,
    difficulty: "intermediate",
    tagline: "Chest and lats stretch-and-pull",
    category: "upper_body",
    setupTip:
      "Lie perpendicular on a flat bench with upper back supported, feet flat. Hold one dumbbell with both hands over your chest, arms nearly straight. Lower the weight in an arc behind your head until arms are about parallel to the floor, then pull it back over your chest.",
    cameraMirror: true,
    imageUrl: "https://cdn.jefit.com/assets/img/exercises/gifs/375.gif",
  },
  {
    id: "rope_tricep_pushdown",
    name: "Rope Tricep",
    wsRoute: "/ws/rope_tricep",
    mode: "reps",
    defaultTarget: 12,
    defaultSets: 3,
    defaultRestSeconds: 60,
    difficulty: "beginner",
    tagline: "Isolated triceps extension with rope",
    category: "upper_body",
    setupTip:
      "Attach a rope to a high pulley. Stand tall, elbows tucked at your sides, forearms parallel to the floor. Push the rope down by extending your elbows, split the rope ends slightly at the bottom, then return under control.",
    cameraMirror: true,
    imageUrl:
      "https://cdn.shopify.com/s/files/1/0618/9462/3460/files/ezgif_com-gif-maker-1.gif",
  },
  {
    id: "sit_up",
    name: "Sit Up",
    wsRoute: "/ws/sit_up",
    mode: "reps",
    defaultTarget: 12,
    defaultSets: 3,
    defaultRestSeconds: 45,
    difficulty: "beginner",
    tagline: "Full-range abdominal curl to seated",
    category: "core",
    setupTip:
      "Lie on your back with knees bent ~90° and feet flat. Cross arms over chest or place hands lightly behind ears. Engage core and curl up one vertebra at a time until torso is near perpendicular, then lower slowly with control.",
    cameraMirror: true,
    imageUrl:
      "https://i0.wp.com/post.healthline.com/wp-content/uploads/2019/05/Traditional-situps.gif?w=1155&h=840",
  },
  {
    id: "lateral_lunge",
    name: "Lateral Lunge",
    wsRoute: "/ws/lateral_lunge",
    mode: "reps",
    defaultTarget: 10,
    defaultSets: 3,
    defaultRestSeconds: 45,
    difficulty: "beginner",
    tagline: "Side-to-side lower-body strength and mobility",
    category: "lower_body",
    setupTip:
      "Stand tall, step one foot out to the side, push your hips back, bend the stepping knee while keeping the opposite leg straight, then push back to center and alternate sides.",
    cameraMirror: true,
    imageUrl: "https://cdn.jefit.com/assets/img/exercises/gifs/1220.gif",
  },
  {
    id: "bulgarian_split_squat",
    name: "Bulgarian Split Squat",
    wsRoute: "/ws/bulgarian_split_squat",
    mode: "reps",
    defaultTarget: 8,
    defaultSets: 3,
    defaultRestSeconds: 60,
    difficulty: "intermediate",
    tagline: "Unilateral quad and glute strength",
    category: "lower_body",
    setupTip:
      "Stand a comfortable distance in front of a bench, place the top of one foot behind you on the bench, lower your hips by bending the front knee, then drive through the front foot to stand.",
    cameraMirror: true,
    imageUrl:
      "https://media4.giphy.com/media/v1.Y2lkPTZjMDliOTUydGQwZDFhNzN3Y2owanRyNGd0bGFhcmdnY2c3djJmODdmNGpqd3Y3biZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/g0Kz180GdPYCsKqMyf/giphy.gif",
  },
  {
    id: "cross_jacks",
    name: "Cross Jacks",
    wsRoute: "/ws/cross_jacks",
    mode: "reps",
    defaultTarget: 20,
    defaultSets: 3,
    defaultRestSeconds: 30,
    difficulty: "beginner",
    tagline: "Full-body cardio and coordination",
    category: "full_body",
    setupTip:
      "Stand with feet apart and arms extended to the sides. Jump while crossing one foot in front of the other and crossing your arms at chest height, then jump back open and alternate sides.",
    cameraMirror: true,
    imageUrl: "https://flabfix.com/wp-content/uploads/2019/06/Cross-Jacks.gif",
  },
  {
    id: "skier_jumping_jacks",
    name: "Skier jumping Jacks",
    wsRoute: "/ws/skier_jumping_jacks",
    mode: "reps",
    defaultTarget: 20,
    defaultSets: 3,
    defaultRestSeconds: 30,
    difficulty: "beginner",
    tagline: "Full-body cardio and coordination",
    category: "full_body",
    setupTip:
      "Stand tall with one foot forward and the other back. Swing the opposite arm forward and the other arm backward, then jump and switch your feet and arms like a cross-country skier.",
    cameraMirror: true,
    imageUrl:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRAhxDHqUKq4voVCaynBMBM-O3a8Q0IYeNmF30OBPKq3Np8bFI2amC8QGfF&s=10",
  },
  {
    id: "squat_jacks",
    name: "Squat Jacks",
    wsRoute: "/ws/squat_jacks",
    mode: "reps",
    defaultTarget: 15,
    defaultSets: 3,
    defaultRestSeconds: 10,
    difficulty: "intermediate",
    tagline: "Explosive squat and cardio movement",
    category: "cardio",
    setupTip:
      "Stand with feet together, jump them wide, and land softly in a squat with hips back and knees bent. Jump back to the starting position and repeat while keeping your chest lifted.",
    cameraMirror: true,
    imageUrl: "https://i.makeagif.com/media/1-27-2017/HgSiwz.gif",
  },
  {
    id: "battle_rope_cardio",
    name: "Battle Rope Cardio",
    wsRoute: "/ws/battle_rope_cardio",
    mode: "hold",
    defaultTarget: 30,
    defaultSets: 3,
    defaultRestSeconds: 10,
    difficulty: "beginner",
    tagline: "Full-body cardio and upper-body conditioning",
    category: "cardio",
    setupTip:
      "Stand with feet shoulder-width apart, knees slightly bent, and core engaged. Hold one rope end in each hand and rapidly alternate raising and lowering your arms to create continuous waves.",
    cameraMirror: true,
    imageUrl:
      "https://hips.hearstapps.com/hmg-prod/images/gettyimages-657495548-1527710829.jpg?crop=0.6674528301886793xw:1xh;center,top&resize=1200:*",
  },
  {
    id: "line_hop",
    name: "Line Hop",
    wsRoute: "/ws/line_hop",
    mode: "reps",
    defaultTarget: 20,
    defaultSets: 3,
    defaultRestSeconds: 30,
    difficulty: "beginner",
    tagline: "Side-to-side hopping for agility and cardio",
    category: "cardio",
    setupTip:
      "Place an imaginary or visible line on the floor. Stand beside it with knees slightly bent, then hop side to side over the line, landing softly and maintaining a steady rhythm.",
    cameraMirror: true,
    imageUrl:
      "https://app-media.fitbod.me/v2/3383/images/landscape/0_960x540.jpg",
  },
  {
    id: "knee_strike",
    name: "Knee Strike",
    wsRoute: "/ws/knee_strike",
    mode: "reps",
    defaultTarget: 20,
    defaultSets: 3,
    defaultRestSeconds: 30,
    difficulty: "beginner",
    tagline: "Full-body cardio with alternating knee drive",
    category: "cardio",
    setupTip:
      "Stand tall with a soft bend in your knees and hands near chest height. Drive one knee upward toward hip level while keeping your torso controlled, lower it, then alternate sides without striking a person or object.",
    cameraMirror: true,
    imageUrl:
      "https://i.pinimg.com/originals/6d/64/08/6d6408cca5ae5d77d8bab4881deecb59.gif",
  },
  {
    id: "dumbbell_reverse_fly",
    name: "Dumbbell Reverse Fly",
    wsRoute: "/ws/dumbbell_reverse_fly",
    mode: "reps",
    defaultTarget: 12,
    defaultSets: 3,
    defaultRestSeconds: 60,
    difficulty: "beginner",
    tagline: "Rear deltoid and upper-back isolation",
    category: "upper_body",
    setupTip:
      "Hold a dumbbell in each hand, hinge forward with a flat back, keep your knees slightly bent and elbows softly bent. Raise the dumbbells out to the sides until your arms are near shoulder height, squeeze your upper back, then lower slowly.",
    cameraMirror: true,
    imageUrl:
      "https://media2.giphy.com/media/v1.Y2lkPTZjMDliOTUyaHFyeGExcXdpdHlwcXY2MDI0bW1iOGxxMTV6cHNnczRjMTdjcTM4biZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/cJboHdxNDIySmj8DTS/source.gif",
  },
  {
    id: "skipping",
    name: "Skipping",
    wsRoute: "/ws/skipping",
    mode: "reps",
    defaultTarget: 30,
    defaultSets: 3,
    defaultRestSeconds: 30,
    difficulty: "beginner",
    tagline: "Full-body jump-rope cardio and coordination",
    category: "cardio",
    setupTip:
      "Stand tall with feet close together, elbows near your sides, and hands around waist height. Rotate the rope with your wrists while making small, soft jumps on the balls of your feet.",
    cameraMirror: true,
    imageUrl:
      "https://flabfix.com/wp-content/uploads/2019/06/Invisible-Jump-Rope.gif",
  },
  {
    id: "alternating-toe-touch",
    name: "Alternating Toe Touch",
    wsRoute: "/ws/alternating_toe_touch",
    mode: "reps",
    defaultTarget: 20,
    defaultSets: 3,
    defaultRestSeconds: 30,
    difficulty: "beginner",
    tagline: "Controlled core exercise for abs, obliques, and coordination",
    category: "core",
    setupTip:
      "Lie on your back with your legs extended upward and arms reaching overhead. Brace your core, then lift your shoulder blades and reach your right hand toward your left foot. Return with control and alternate sides while keeping your neck neutral and lower back stable.",
    cameraMirror: true,
    imageUrl: "https://i.ytimg.com/vi/hfITeQzFP9s/maxresdefault.jpg",
  },
  {
    id: "standing_side_leg_raise",
    name: "Standing Side Leg Raise",
    wsRoute: "/ws/standing_side_leg_raise",
    mode: "reps",
    defaultTarget: 12,
    defaultSets: 3,
    defaultRestSeconds: 30,
    difficulty: "beginner",
    tagline: "Hip abductor and outer-glute strengthening",
    category: "lower_body",
    setupTip:
      "Stand tall with feet together and hold a wall or chair for balance if needed. Shift your weight onto one leg, lift the other leg straight out to the side with toes facing forward, then lower it slowly without leaning your torso.",
    cameraMirror: true,
    imageUrl:
      "https://cdn.motra.com/exercise-assets/cf23f8b081/thumbnailOriginal.jpg",
  },
  {
    id: "hamstring_curl",
    name: "Hamstring Curl",
    wsRoute: "/ws/hamstring_curl",
    mode: "reps",
    defaultTarget: 12,
    defaultSets: 3,
    defaultRestSeconds: 45,
    difficulty: "beginner",
    tagline: "Hamstring isolation and knee stability",
    category: "lower_body",
    setupTip:
      "Stand tall and hold a wall or chair for balance. Shift your weight onto one leg, bend the other knee, and bring your heel toward your glutes, then lower it slowly. Keep your thighs parallel and avoid arching your back.",
    cameraMirror: true,
    imageUrl:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTiBoH-r0T9jhLpRystrMQTIwfzE6oSyorkv0sN7NoS3ySPgq55nezOSUXa&s=10",
  },
  {
    id: "standing_hamstring_curl",
    name: "Standing Hamstring Curl",
    wsRoute: "/ws/standing_hamstring_curl",
    mode: "reps",
    defaultTarget: 12,
    defaultSets: 3,
    defaultRestSeconds: 45,
    difficulty: "beginner",
    tagline: "Single-leg hamstring isolation in standing",
    category: "lower_body",
    setupTip:
      "Stand tall with feet hip-width apart and hold a wall or chair for balance. Shift your weight onto one leg, bend the other knee, and bring your heel toward your glutes while keeping your thighs parallel, then lower slowly.",
    cameraMirror: true,
    imageUrl:
      "https://images.squarespace-cdn.com/content/v1/5f5e8592d2b0854b18af6975/11fe7089-63b3-427a-bf08-adf4ada0bd66/standing+dumbbell+hamstring+curl.jpg",
  },
  {
    id: "lying_chest_fly",
    name: "Lying Chest Fly",
    wsRoute: "/ws/lying_chest_fly",
    mode: "reps",
    defaultTarget: 10,
    defaultSets: 3,
    defaultRestSeconds: 60,
    difficulty: "intermediate",
    tagline: "Chest isolation with wide arc",
    category: "upper_body",
    setupTip:
      "Lie on a flat bench with feet planted, holding a dumbbell in each hand above your chest, palms facing each other and elbows slightly bent. Lower your arms out to the sides in a wide arc until dumbbells are roughly chest-level, then squeeze your chest to bring them back up.",
    cameraMirror: true,
    imageUrl:
      "https://media.post.rvohealth.io/wp-content/uploads/2022/08/Dumbbell-chest-fly.gif",
  },
  {
    id: "lying_chest_press",
    name: "Lying Chest Press",
    wsRoute: "/ws/lying_chest_press",
    mode: "reps",
    defaultTarget: 10,
    defaultSets: 3,
    defaultRestSeconds: 60,
    difficulty: "beginner",
    tagline: "Flat dumbbell press for chest strength",
    category: "upper_body",
    setupTip:
      "Lie on a flat bench with feet firmly on the floor, holding a dumbbell in each hand at chest level, elbows bent ~90° and slightly away from your torso. Press the weights up over your mid-chest until arms are nearly straight, then lower slowly back to the starting position.",
    cameraMirror: true,
    imageUrl:
      "https://cdn.muscleandstrength.com/sites/default/files/dumbbell-floor-press-thumb.jpg",
  },
  {
    id: "frog_jumps",
    name: "Frog Jumps",
    wsRoute: "/ws/frog_jumps",
    mode: "reps",
    defaultTarget: 12,
    defaultSets: 3,
    defaultRestSeconds: 60,
    difficulty: "intermediate",
    tagline: "Explosive squat jump for lower body and cardio",
    category: "lower_body",
    setupTip:
      "Start in a deep squat with feet slightly wider than shoulder-width, hips low, and hands touching or near the floor in front of you. Explosively jump upward, swinging arms overhead, then land softly back into the deep squat position.",
    cameraMirror: true,
    imageUrl:
      "https://i.pinimg.com/originals/9d/bb/86/9dbb86c5e1d59fc612bbb1e805a237ac.gif",
  },
  {
    id: "burpees",
    name: "Burpees",
    wsRoute: "/ws/burpees",
    mode: "reps",
    defaultTarget: 10,
    defaultSets: 3,
    defaultRestSeconds: 60,
    difficulty: "intermediate",
    tagline: "Full-body squat–plank–jump combo",
    category: "full_body",
    setupTip:
      "Stand with feet shoulder-width apart. Squat down and place your hands on the floor, jump your feet back into a plank, optionally perform a push-up, jump your feet forward back to a squat, then explode up into a jump with arms overhead.",
    cameraMirror: true,
    imageUrl: "",
  },
  {
    id: "squat_thrusts",
    name: "Squat Thrusts",
    wsRoute: "/ws/squat_thrusts",
    mode: "reps",
    defaultTarget: 12,
    defaultSets: 3,
    defaultRestSeconds: 60,
    difficulty: "intermediate",
    tagline: "Full-body squat–plank–stand without push-up",
    category: "full_body",
    setupTip:
      "Stand with feet shoulder-width apart. Squat down and place your hands on the floor in front of your feet, then jump your feet back into a plank. Briefly hold, jump your feet back toward your hands into a squat, and stand up tall to finish each rep.",
    cameraMirror: true,
    imageUrl: "",
  },
];

export function getExerciseById(id: string): ExerciseConfig | undefined {
  return exercises.find((e) => e.id === id);
}
